// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/wallet/v1/wallet.proto

package walletv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 2
	UserStatus_USER_STATUS_CLOSED      UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_CLOSED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_CLOSED":      3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_wallet_v1_wallet_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_api_proto_wallet_v1_wallet_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_wallet_v1_wallet_proto_rawDescGZIP(), []int{0}
}

type GetUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	mi := &file_api_proto_wallet_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_v1_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           UserStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=wallet.v1.UserStatus" json:"status,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	BlockedAmount    float64                `protobuf:"fixed64,6,opt,name=blocked_amount,json=blockedAmount,proto3" json:"blocked_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserBalanceResponse) Reset() {
	*x = UserBalanceResponse{}
	mi := &file_api_proto_wallet_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceResponse) ProtoMessage() {}

func (x *UserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceResponse.ProtoReflect.Descriptor instead.
func (*UserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *UserBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBalanceResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *UserBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UserBalanceResponse) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserBalanceResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *UserBalanceResponse) GetBlockedAmount() float64 {
	if x != nil {
		return x.BlockedAmount
	}
	return 0
}

var File_api_proto_wallet_v1_wallet_proto protoreflect.FileDescriptor

const file_api_proto_wallet_v1_wallet_proto_rawDesc = "" +
	"\n" +
	" api/proto/wallet/v1/wallet.proto\x12\twallet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x15GetUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8c\x02\n" +
	"\x13UserBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\x01R\x10availableBalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.wallet.v1.UserStatusR\x06status\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12%\n" +
	"\x0eblocked_amount\x18\x06 \x01(\x01R\rblockedAmount*t\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x16\n" +
	"\x12USER_STATUS_CLOSED\x10\x032_\n" +
	"\rWalletService\x12N\n" +
	"\n" +
	"GetBalance\x12 .wallet.v1.GetUserBalanceRequest\x1a\x1e.wallet.v1.UserBalanceResponseBWZUgithub.com/LuigiEnzoFerrari/servers/bff/dashboard_server/api/proto/wallet/v1;walletv1b\x06proto3"

var (
	file_api_proto_wallet_v1_wallet_proto_rawDescOnce sync.Once
	file_api_proto_wallet_v1_wallet_proto_rawDescData []byte
)

func file_api_proto_wallet_v1_wallet_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_v1_wallet_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wallet_v1_wallet_proto_rawDesc), len(file_api_proto_wallet_v1_wallet_proto_rawDesc)))
	})
	return file_api_proto_wallet_v1_wallet_proto_rawDescData
}

var file_api_proto_wallet_v1_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_wallet_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_wallet_v1_wallet_proto_goTypes = []any{
	(UserStatus)(0),               // 0: wallet.v1.UserStatus
	(*GetUserBalanceRequest)(nil), // 1: wallet.v1.GetUserBalanceRequest
	(*UserBalanceResponse)(nil),   // 2: wallet.v1.UserBalanceResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proto_wallet_v1_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.v1.UserBalanceResponse.status:type_name -> wallet.v1.UserStatus
	3, // 1: wallet.v1.UserBalanceResponse.last_updated:type_name -> google.protobuf.Timestamp
	1, // 2: wallet.v1.WalletService.GetBalance:input_type -> wallet.v1.GetUserBalanceRequest
	2, // 3: wallet.v1.WalletService.GetBalance:output_type -> wallet.v1.UserBalanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_v1_wallet_proto_init() }
func file_api_proto_wallet_v1_wallet_proto_init() {
	if File_api_proto_wallet_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wallet_v1_wallet_proto_rawDesc), len(file_api_proto_wallet_v1_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_wallet_v1_wallet_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_v1_wallet_proto_depIdxs,
		EnumInfos:         file_api_proto_wallet_v1_wallet_proto_enumTypes,
		MessageInfos:      file_api_proto_wallet_v1_wallet_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_v1_wallet_proto = out.File
	file_api_proto_wallet_v1_wallet_proto_goTypes = nil
	file_api_proto_wallet_v1_wallet_proto_depIdxs = nil
}
